cubeeye_camera_node:
  ros__parameters:
    amplitude_threshold_max: 5000 # Capped slightly below max to filter out fully saturated pixels which cause depth artifacts
    amplitude_threshold_min: 100 # High minimum threshold because white objects at close range have very strong signals. This aggressively cuts out noise and background.
    auto_exposure: true 
    autorun_onoff: true
    autorun_serialnumber: I200DU2608000073
    autorun_frametype: 38
    depth_range_max: 350 #fino a 35cm
    depth_range_min: 200 #da 20 cm
    flying_pixel_remove_filter: true
    flying_pixel_remove_threshold: 200
    framerate: 15
    integration_time: 1000 # non serve a nulla, non c'è modo di modificare questo parametro
    median_filter: true
    noise_removal_threshold: 50
    outlier_remove_filter: true
    phase_noise_filter: false
    qos_overrides./parameter_events.publisher.depth: 1000
    qos_overrides./parameter_events.publisher.durability: volatile
    qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: reliable
    scattering_filter: false 
    scattering_filter_threshold: 700
    use_sim_time: false
